title: Jenry Luis # your name (or website title) here
logo: "/images/foto-git-removebg-preview.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with 1+ year of experience developing personal projects to show my technical skills in analytics. More than a year ago I decided to redirect my professional career, taking Python, Machine Learning, and Big Data specialization courses.
  <br><br>
  <a href="https://www.linkedin.com/in/jenry-luis-v/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
