title: DS # your name (or website title) here
#logo: "/images/foto-git-removebg-preview.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  
  <br><br>
  
  <br>
  
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
# Data Scientist with 1+ year of experience developing personal projects to show my technical skills in analytics. I took Python, Machine Learning, and Big Data specialization courses to reorient my professional career.
#Email: jenry.luis@gmail.com
#Teléfono: (+51) 944272292
#<a href="https://www.linkedin.com/in/jenry-luis-v/">View My LinkedIn Profile</a>

# 6 years of experience as Core Network Engineer, I am currently exploring Python language to develop some personal projects
