title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist
  <br><br>
  More than a year ago I decided to redirect my professional career, taking Data Science, Machine Learning, and Big Data specialization courses. Since then, I have been developing personal projects to improve my analytical skills
  <br><br>
  <a href="https://www.linkedin.com/in/jenry-luis-v/">View My LinkedIn Profile</a>
  <br><br>
  <a>Python -</a> <a>SQL - </a> <a>GCP </a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
